In [1]:
import numpy as np

In [3]:
matriksA = np.array([[1,2], [3,2]])
print(matriksA)

[[1 2]
 [3 2]]


In [4]:
matriksB = np.array([[5,2], [1,6]])
print(matriksB)

[[5 2]
 [1 6]]


In [5]:
matriksC = matriksA + matriksB
print(matriksC)

[[6 4]
 [4 8]]


In [6]:
matriksD = matriksA - matriksB
print(matriksD)

[[-4  0]
 [ 2 -4]]


In [7]:
matriksE = np.dot(matriksA, matriksB)
print(matriksE)

[[ 7 14]
 [17 18]]


In [12]:
matriksF = np.linalg.det([[1, 2],[3, 2]])
print(matriksF)

-4.000000000000001


In [13]:
matriksG = np.array([[1,1],[2,1],[3,3]])
print(matriksG.transpose())

[[1 2 3]
 [1 1 3]]
